# Generated by Django 3.1.5 on 2021-04-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
